### ISSUE TITLE
Duplicates | empty ngrams in short documents with limited characters

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/polmineR.misc#12]
**Summary**: The method to identify duplicates might require sufficiently long documents.

If I am not mistaken, the following line introduces a complication concerning the comparison of ngrams:

https://github.com/PolMine/polmineR.misc/blob/03dfef42f3242ce3120a45f283a61b89ebb903d4/R/Duplicates.R#L340

For each subcorpus in x, the function returns a data.table which contains the frequency of ngrams limited by the character selection in `char`. These ngrams do not need to be of length `n` however. They can be between 0 and 5 characters long if I am not mistaken.

Here, for short documents it is possible that the function returns data.tables which contain only 0-length ngrams. For example, a document might contain 6 "empty" ngrams and nothing else. I think this happens if the `char` argument limits the characters to those which are not present (at least not in sufficent numbers) in a document. 

This results in documents which seem very different to have a high similarity score because their similiarity is calculated based on the "empty" ngrams alone. This is a problem for shorter documents which might not contain some of the letters in `char` and not many ngrams in general.

I am not sure how to address this but sometimes, for very short documents, this might identify false duplicates.

**Comment by ablaette** [comment]
Absolutely valid point. This is a set of articles in line with your scenario.

|article_id        | fulltext |
|--------------|------------------------------|
| A101396944 | SZ vom 02.01.1987 , Seite 16 |
| A101396951 | SZ vom 02.01.1987 , Seite 23 |
| A101396952 | SZ vom 02.01.1987 , Seite 24 |
| A101396953 | SZ vom 02.01.1987 , Seite 25 |
| A101396967 | SZ vom 02.01.1987 , Seite 39 |51 | SZ vom 02.01.1987 , Seite 23 |
| A101396952 | SZ vom 02.01.1987 , Seite 24 |
| A101396953 | SZ vom 02.01.1987 , Seite 25 |
| A101396967 | SZ vom 02.01.1987 , Seite 39 |

**Comment by ablaette** [comment]
I have implemented two solutions now: 

- Method `Duplicates$detect()` has a new argument `min_shingle_length` that will check against the length of the shingles. This may preclude that identification of very short documents following a similar pattern as duplicates.
- Method `Duplicates$make_annotation_data()` has a new argument `drop` that can be used to pass a vector with document IDs to be excluded.

**Comment by ablaette** [comment]
`Duplicates$make_annotation_data()` now has argument `drop` to remove short articles deliberately. 

`Duplicate$detect()` has argument `min_shingle_length`.
